# Generated by Django 3.2.5 on 2021-07-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_page_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='video',
        ),
    ]
