# Generated by Django 3.2.5 on 2021-08-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_page_content2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content2',
        ),
    ]
