# Generated by Django 3.2.5 on 2021-09-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0008_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='url',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='url1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
